language: python
python: 3.6

before_install:
  - sudo pip install pipenv

install:
  - pipenv install --dev

stages:
  - test

jobs:
  include:
    - stage: test

      script:
        - pipenv run tests

notifications:
  email: false
